### ISSUE TITLE
Is this a fork?

### ISSUE THREAD

**Issue by barryrowlingson** [s-fleck/lest#1]
Your text says "forked from dplyr" but I don't see any similarity in the code for `case_when`. Did you take any code from dplyr by forking the codebase or have you reimplemented things from scratch? I don't see any credit to any dplyr authors in your DESCRIPTION either.

Great to see low-dependency packages!

**Comment by s-fleck** [comment]
It is basically just the function extracted from (and older version) of  dplyr with some minor refactoring. Your right I probably should add the dplyr authors to the description. Back when I made the package I wasn't really sure how to go about crediting.

`case_when()` and `if_else()` are copy, paste and refactor jobs.

`cumall()`, `cumany()` are a complete rewrites of the original functions in plain c to get rid of the Rcpp dependency. In fact, the current `cumall()` and `cumany()` implementation in dplyr is based on a pull request by me, due to a bug I discovered in the way it handled NAs it when I developed lest.

edit: more history
